// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/google/wire"
	"github.com/qhuongng/wnc-todo/tree/add-redux/backend/internal/controller"
	"github.com/qhuongng/wnc-todo/tree/add-redux/backend/internal/controller/http"
	"github.com/qhuongng/wnc-todo/tree/add-redux/backend/internal/controller/http/v1"
	"github.com/qhuongng/wnc-todo/tree/add-redux/backend/internal/database"
	"github.com/qhuongng/wnc-todo/tree/add-redux/backend/internal/repository/implement"
	"github.com/qhuongng/wnc-todo/tree/add-redux/backend/internal/service/implement"
)

// Injectors from wire.go:

func InitializeContainer(db database.Db) *controller.ApiContainer {
	userRepository := repositoryimplement.NewUserRepository(db)
	userService := serviceimplement.NewUserService(userRepository)
	userHandler := v1.NewUserHandler(userService)
	todoRepository := repositoryimplement.NewTodoRepository(db)
	todoService := serviceimplement.NewTodoService(todoRepository)
	todoHandler := v1.NewTodoHandler(todoService, userService)
	server := http.NewServer(userHandler, todoHandler)
	apiContainer := controller.NewApiContainer(server)
	return apiContainer
}

// wire.go:

var container = wire.NewSet(controller.NewApiContainer)

// may have grpc server in the future
var serverSet = wire.NewSet(http.NewServer)

// handler === controller | with service and repository layers to form 3 layers architecture
var handlerSet = wire.NewSet(v1.NewUserHandler, v1.NewTodoHandler)

var serviceSet = wire.NewSet(serviceimplement.NewUserService, serviceimplement.NewTodoService)

var repositorySet = wire.NewSet(repositoryimplement.NewUserRepository, repositoryimplement.NewTodoRepository)
